import base64, hashlib, json, os, textwrap, zlib

import os
_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SPEC = os.path.join(_ROOT, "specs", "madi_affector_torus.asset.json")
OUT  = os.path.join(_ROOT, "app", "nsfw_spec.py")

with open(SPEC, encoding="utf-8") as fh:
    asset = json.load(fh)

raw = json.dumps(asset, separators=(",", ":"), sort_keys=True).encode("utf-8")
packed = base64.b64encode(zlib.compress(raw, 9)).decode("ascii")
digest = hashlib.sha256(raw).hexdigest()

header = '''"""Embedded rig specs for the NSFW Tools tab.

WHAT THIS IS: a node group, a mesh and a modifier stack, packed as data. The
Blender add-on carries only a GENERIC builder (assets.py) that follows a spec it
is handed - so the add-on can be read all day without revealing anything, and
the recipe travels only from this licensed build.

⚠ WHAT IT IS NOT: a way to hide the rig once it is built. A node group in
someone's file can always be opened and read - Blender has no encryption and no
lock. What this buys is that the recipe never SHIPS readable: not as a .blend,
not as add-on source. Naming the built group with a leading "." keeps it out of
Blender's ID browsers, which is discoverability, not security.

Generated by tools\\\\pack_spec.py from specs\\\\madi_affector_torus.asset.json -
do not hand-edit. Re-capture from Blender and re-pack instead.
"""

import base64
import json
import zlib

'''

body = 'ASSET_SHA256 = "%s"\n\n' % digest
body += "# %s: %d nodes, %d links, %d verts. %.1f KB packed from %.1f KB of JSON.\n" % (
    asset["label"], asset["group"]["counts"]["nodes"], asset["group"]["counts"]["links"],
    len(asset["object"]["mesh"]["verts"]) // 3, len(packed) / 1024, len(raw) / 1024)
body += "_PACKED = (\n"
for line in textwrap.wrap(packed, 96):
    body += '    "%s"\n' % line
body += ")\n\n\n"
body += '''def packed():
    """The spec exactly as the bridge wants it - base64 of zlib of JSON.

    Handed straight to the add-on without unpacking here: the app has no reason
    to hold half a megabyte of plaintext rig in memory.
    """
    return _PACKED


def asset():
    """The unpacked spec, for the parts the UI needs (labels, defaults, names)."""
    return json.loads(zlib.decompress(base64.b64decode(_PACKED)).decode("utf-8"))
'''

with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
    fh.write(header + body)

print("wrote %s" % OUT)
print("  packed %.1f KB  (from %.1f KB raw, ratio %.3f)" % (len(packed)/1024, len(raw)/1024, len(packed)/len(raw)))
print("  sha256 %s" % digest[:16])
print("  file   %.1f KB" % (os.path.getsize(OUT)/1024))
